dpr_id_map = "/fs/clip-scratch/entilzha/fever/dpr_fever_wikipedia_id_map.json"

# Original Fever Data
[fever.train]
examples = "data/train.jsonl"
kotlin_examples = "data/train.kotlin.json"

[fever.dev]
examples = "data/shared_task_dev.jsonl"
kotlin_examples = "data/shared_task_dev.kotlin.jsonl"

# Lucene Data and Predictions
[lucene.train]
preds = "data/lucene_preds_train.jsonl"
metrics = "data/lucene/metrics.train.json"

[lucene.dev]
preds = "data/lucene_preds_dev.jsonl"
metrics = "data/lucene/metrics.dev.json"

[retriever.claim_only.dev]
verify_examples = "data/shared_task_dev.jsonl"

[verifier.claim_only]
serialization_dir = '/fs/clip-scratch/entilzha/verifier-models/claim_only.model'
archive = '/fs/clip-scratch/entilzha/verifier-models/claim_only.model/model.tar.gz'
config = 'claim_only.jsonnet'
overrides = {}

[pipeline.'claim_only+claim_only'.dev]
preds = '/fs/clip-scratch/entilzha/pipeline/claim_only/preds_dev.jsonl'
confusion = '/fs/clip-scratch/entilzha/pipeline/claim_only/confusion.dev.png'
metrics = '/fs/clip-scratch/entilzha/pipeline/claim_only/metrics.dev.json'

# Fever Verifier Models
[verifier.batch]
serialization_dir = '/fs/clip-scratch/entilzha/verifier-models/verifier-batch.model'
archive = '/fs/clip-scratch/entilzha/verifier-models/verifier-batch.model/model.tar.gz'
config = 'verifier_in_batch.jsonnet'
overrides = {}


# DPR models for Fever
# verify_examples: Store the claims and evidence predictins here for easy evaluation
# with a model that only does claim verification
[retriever.dpr_neg_0.train]
hard_neg = '/fs/clip-quiz/entilzha/code/fever/data/dpr.hard_neg_0.train.json'

[retriever.dpr_neg_0.dev]
evidence_preds = "/fs/clip-scratch/entilzha/dpr-predictions/pretrain-fever/preds_dev.json"
verify_examples = "/fs/clip-scratch/entilzha/dpr-predictions/pretrain-fever/shared_task_dev.jsonl"
metrics = "/fs/clip-scratch/entilzha/dpr-predictions/pretrain-fever/metrics.json"
hard_neg = '/fs/clip-quiz/entilzha/code/fever/data/dpr.hard_neg_0.dev.json'


[retriever.dpr_neg_1.train]
hard_neg = '/fs/clip-quiz/entilzha/code/fever/data/dpr.hard_neg_1.train.json'

[retriever.dpr_neg_1.dev]
evidence_preds = "/fs/clip-scratch/entilzha/dpr-predictions/pretrain-negs_1/preds_dev.json"
verify_examples = "/fs/clip-scratch/entilzha/dpr-predictions/pretrain-negs_1/shared_task_dev.jsonl"
metrics = "/fs/clip-scratch/entilzha/dpr-predictions/pretrain-negs_1/metrics.json"
hard_neg = '/fs/clip-quiz/entilzha/code/fever/data/dpr.hard_neg_1.dev.json'


[retriever.dpr_neg_2.train]
hard_neg = '/fs/clip-quiz/entilzha/code/fever/data/dpr.hard_neg_2.train.json'

[retriever.dpr_neg_2.dev]
evidence_preds = "/fs/clip-scratch/entilzha/dpr-predictions/pretrain-negs_2/preds_dev.json"
verify_examples = "/fs/clip-scratch/entilzha/dpr-predictions/pretrain-negs_2/shared_task_dev.jsonl"
metrics = "/fs/clip-scratch/entilzha/dpr-predictions/pretrain-negs_2/metrics.json"
hard_neg = '/fs/clip-quiz/entilzha/code/fever/data/dpr.hard_neg_2.dev.json'


[retriever.dpr_neg_3.train]
hard_neg = '/fs/clip-quiz/entilzha/code/fever/data/dpr.hard_neg_3.train.json'

[retriever.dpr_neg_3.dev]
evidence_preds = "/fs/clip-scratch/entilzha/dpr-predictions/pretrain-negs_3/preds_dev.json"
verify_examples = "/fs/clip-scratch/entilzha/dpr-predictions/pretrain-negs_3/shared_task_dev.jsonl"
metrics = "/fs/clip-scratch/entilzha/dpr-predictions/pretrain-negs_3/metrics.json"
hard_neg = '/fs/clip-quiz/entilzha/code/fever/data/dpr.hard_neg_3.dev.json'

[retriever.dpr_neg_4.train]
hard_neg = '/fs/clip-quiz/entilzha/code/fever/data/dpr.hard_neg_4.train.json'

[retriever.dpr_neg_4.dev]
evidence_preds = "/fs/clip-scratch/entilzha/dpr-predictions/pretrain-negs_4/preds_dev.json"
verify_examples = "/fs/clip-scratch/entilzha/dpr-predictions/pretrain-negs_4/shared_task_dev.jsonl"
metrics = "/fs/clip-scratch/entilzha/dpr-predictions/pretrain-negs_4/metrics.json"
hard_neg = '/fs/clip-quiz/entilzha/code/fever/data/dpr.hard_neg_4.dev.json'


[retriever.dpr_neg_5.train]
hard_neg = '/fs/clip-quiz/entilzha/code/fever/data/dpr.hard_neg_5.train.json'

[retriever.dpr_neg_5.dev]
evidence_preds = "/fs/clip-scratch/entilzha/dpr-predictions/pretrain-negs_5/preds_dev.json"
verify_examples = "/fs/clip-scratch/entilzha/dpr-predictions/pretrain-negs_5/shared_task_dev.jsonl"
metrics = "/fs/clip-scratch/entilzha/dpr-predictions/pretrain-negs_5/metrics.json"
hard_neg = '/fs/clip-quiz/entilzha/code/fever/data/dpr.hard_neg_5.dev.json'

[pipeline.'dpr_neg_0+batch'.dev]
preds = '/fs/clip-scratch/entilzha/pipeline/dpr_neg_0+batch/preds_dev.jsonl'
confusion = '/fs/clip-scratch/entilzha/pipeline/dpr_neg_0+batch/confusion.png'
metrics = '/fs/clip-scratch/entilzha/pipeline/dpr_neg_0+batch/metrics.dev.json'

[pipeline.'dpr_neg_1+batch'.dev]
preds = '/fs/clip-scratch/entilzha/pipeline/dpr_neg_1+batch/preds_dev.jsonl'
confusion = '/fs/clip-scratch/entilzha/pipeline/dpr_neg_1+batch/confusion.png'
metrics = '/fs/clip-scratch/entilzha/pipeline/dpr_neg_1+batch/metrics.dev.json'

[pipeline.'dpr_neg_2+batch'.dev]
preds = '/fs/clip-scratch/entilzha/pipeline/dpr_neg_2+batch/preds_dev.jsonl'
confusion = '/fs/clip-scratch/entilzha/pipeline/dpr_neg_2+batch/confusion.png'
metrics = '/fs/clip-scratch/entilzha/pipeline/dpr_neg_2+batch/metrics.dev.json'

[pipeline.'dpr_neg_3+batch'.dev]
preds = '/fs/clip-scratch/entilzha/pipeline/dpr_neg_3+batch/preds_dev.jsonl'
confusion = '/fs/clip-scratch/entilzha/pipeline/dpr_neg_3+batch/confusion.png'
metrics = '/fs/clip-scratch/entilzha/pipeline/dpr_neg_3+batch/metrics.dev.json'

[pipeline.'dpr_neg_4+batch'.dev]
preds = '/fs/clip-scratch/entilzha/pipeline/dpr_neg_4+batch/preds_dev.jsonl'
confusion = '/fs/clip-scratch/entilzha/pipeline/dpr_neg_4+batch/confusion.png'
metrics = '/fs/clip-scratch/entilzha/pipeline/dpr_neg_4+batch/metrics.dev.json'

[pipeline.'dpr_neg_5+batch'.dev]
preds = '/fs/clip-scratch/entilzha/pipeline/dpr_neg_5+batch/preds_dev.jsonl'
confusion = '/fs/clip-scratch/entilzha/pipeline/dpr_neg_5+batch/confusion.png'
metrics = '/fs/clip-scratch/entilzha/pipeline/dpr_neg_5+batch/metrics.dev.json'